language: node_js

node_js:
- "6"

script:
- yarn run pack
- yarn run build:darwin
- zip -r bulk-translator-2-darwin-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip build/bulk-translator-2-darwin-x64
- yarn run build:linux
- zip -r bulk-translator-2-linux-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip build/bulk-translator-2-linux-x64

deploy:
  provider: releases
  api_key:
    secure: BQoHxonhmqQq3y8Bscgz
  file:
    - bulk-translator-2-darwin-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip
    - bulk-translator-2-linux-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true