language: node

script:
- npm run pack
- npm run build:win32
- cd build/bulk-translator-2-win32-x64
- zip bulk-translator-2-win32-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER} *
- cd ../..
- npm run build:darwin
- cd build/bulk-translator-2-darwin-x64
- zip bulk-translator-2-darwin-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER} *
- cd ../..
- npm run build:linux
- cd build/bulk-translator-2-linux-x64
- zip bulk-translator-2-linux-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER} *
- cd ../..

deploy:
  provider: releases
  api_key:
    secure: BQoHxonhmqQq3y8Bscgz
  file:
    - build/bulk-translator-2-win32-x64/bulk-translator-2-win32-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip
    - build/bulk-translator-2-darwin-x64/bulk-translator-2-darwin-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip
    - build/bulk-translator-2-linux-x64/bulk-translator-2-linux-x64-${TRAVIS_TAG}-build-${TRAVIS_BUILD_NUMBER}.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true