platform:
  - x64

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - ps: get-process -Name node -ErrorAction Ignore
  - npm install

build_script:
- npm run pack
 # - npm run build:win32
 # - npm run build:linux		
- npm run build:darwin
- tasklist
#- ps: get-process -Name node -ErrorAction Ignore
#- ps: stop-process -Name node -ErrorAction Ignore
 # - powershell.exe get-process -Name node -ErrorAction Ignore
 # - powershell.exe stop-process -Name node -ErrorAction Ignore
 # - powershell.exe get-process -Name node -ErrorAction Ignore

artifacts:
#  - path: build\bulk-translator-2-win32-x64
#  - path: build\bulk-translator-2-linux-x64		
  - path: build\bulk-translator-2-darwin-x64		

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
