platform:
  - x64

skip_non_tags: true

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - cmd /c npm run pack
  - cmd /c npm run build:win32
  - cmd /c npm run build:linux		
  - cmd /c npm run build:darwin

test_script:
  - ps: get-process | findstr /psi "node"  
  - ps: Stop-Process -Name node
  - ps: get-process | findstr /psi "node"

artifacts:
- path: build\bulk-translator-2-win32-x64
- path: build\bulk-translator-2-linux-x64		
- path: build\bulk-translator-2-darwin-x64		

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
