platform:
  - x64

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - npm run pack
  - npm run build:win32
  - npm run build:linux		
  - npm run build:darwin
  - process.exit(0)
  - powershell get-process | findstr /psi "node"  
  - powershell stop-process -Name node -erroraction ignore
  - powershell get-process | findstr /psi "node"

artifacts:
  - path: build\bulk-translator-2-win32-x64
  - path: build\bulk-translator-2-linux-x64		
  - path: build\bulk-translator-2-darwin-x64		

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
