platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - npm run pack
  - npm run build:win32

test: off

artifacts:
- path: build\bulk-translator-2-win32-x64


deploy:
- provider: GitHub
  auth_token:
    secure: XzF+tv+eNt5kVFVCR+vRzieXMuQuiIm59sNqopHv9w3VXu9Watx7fn/s+r93nVF0
  artifact: build\bulk-translator-2-win32-x64