platform:
  - x64

skip_non_tags: true

init:
  - git config --global core.autocrlf input

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - npm install

build_script:
  - npm run pack
  - npm run build:win32

test: off

artifacts:
- path: build\bulk-translator-2-win32-x64
  name: bulk-translator-2-win32-x64-$(APPVEYOR_REPO_TAG_NAME)-build-$(APPVEYOR_BUILD_NUMBER)

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
